; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit MPU6050@^2.2.6
  adafruit/Adafruit Unified Sensor@^1.1.15
  adafruit/Adafruit BusIO@^1.17.2
  h2zero/NimBLE-Arduino@^2.3.6
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.3
  adafruit/Adafruit NeoPixel@^1.11.0
  WiFi 
  https://github.com/terrorsl/sMQTTBroker.git

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D MQTT_MAX_PACKET_SIZE=4096
