# -*- coding: utf-8 -*-
"""Perfilamiento_Tesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbJv-Xpp3rsXV3JZs54bescL6mGThKla
"""

# ============================================================
# CELDA 1: Imports y configuracion
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    f1_score, precision_score, recall_score, roc_auc_score, roc_curve
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

SEED = 42
np.random.seed(SEED)

BASE_PATH = "/home/sajaimesp/Tesis_Sistemas/Data_Sets"
print("Configuracion lista.")

# ============================================================
# CELDA 1.5: Descomprimir el dataset
# ============================================================
import zipfile
import os

archivo_zip = f"{BASE_PATH}/uniflow_features.zip"
directorio_destino = BASE_PATH

os.makedirs(directorio_destino, exist_ok=True)
print(f"Descomprimiendo {archivo_zip}...")
try:
    with zipfile.ZipFile(archivo_zip, 'r') as zip_ref:
        zip_ref.extractall(directorio_destino)
    print(f"Archivo {archivo_zip} descomprimido exitosamente en {directorio_destino}.")
except FileNotFoundError:
    print(f"Error: No se encontró el archivo {archivo_zip}. Verifica la ruta.")

# ============================================================
# CELDA 2: Carga del dataset (normal + scan_A)
# ============================================================
df_normal = pd.read_csv(f"{BASE_PATH}/uniflow_normal.csv", low_memory=False)
df_attack = pd.read_csv(f"{BASE_PATH}/uniflow_scan_A.csv", low_memory=False)

print(f"Normal : {df_normal.shape}")
print(f"Scan_A : {df_attack.shape}")
print(f"\nColumnas:\n{list(df_normal.columns)}")

# Verificar que is_attack existe
print(f"\nValores is_attack en normal : {df_normal['is_attack'].value_counts().to_dict()}")
print(f"Valores is_attack en scan_A : {df_attack['is_attack'].value_counts().to_dict()}")

df_raw = pd.concat([df_normal, df_attack], ignore_index=True)
print(f"\nDataset combinado: {df_raw.shape}")

# ============================================================
# CELDA 3: Seleccion de features y limpieza
# ============================================================

# Solo las 13 features que la ESP32 puede extraer de un flujo de red
FLOW_FEATURES = [
    "num_pkts",
    "mean_iat",
    "std_iat",
    "min_iat",
    "max_iat",
    "mean_pkt_len",
    "num_bytes",
    "num_psh_flags",
    "num_rst_flags",
    "num_urg_flags",
    "std_pkt_len",
    "min_pkt_len",
    "max_pkt_len",
]

TARGET = "is_attack"

# Verificar que todas las columnas existen
missing = [c for c in FLOW_FEATURES if c not in df_raw.columns]
if missing:
    print(f"[ERROR] Columnas faltantes: {missing}")
else:
    print(f"Todas las {len(FLOW_FEATURES)} features encontradas.")

df = df_raw[FLOW_FEATURES + [TARGET]].copy()

# Limpiar infinitos y NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)
nan_count = df.isnull().sum()
nan_total = nan_count.sum()
print(f"\nNaN totales: {nan_total}")
if nan_total > 0:
    print(nan_count[nan_count > 0])
    df.fillna(df.median(numeric_only=True), inplace=True)

print(f"\nDataset limpio: {df.shape}")
print(f"\nDistribucion de clases:")
print(f"  Normal (0): {(df[TARGET] == 0).sum()}")
print(f"  Ataque (1): {(df[TARGET] == 1).sum()}")
print(f"  Ratio     : {(df[TARGET] == 1).sum() / len(df) * 100:.1f}% ataques")

# ============================================================
# CELDA 4: Exploracion visual de features
# ============================================================
fig, axes = plt.subplots(3, 2, figsize=(12, 10))

# Features mas relevantes para detectar ataques
plot_feats = ["num_pkts", "mean_iat", "std_iat", "num_bytes", "mean_pkt_len", "max_iat"]

for ax, feat in zip(axes.flatten(), plot_feats):
    for label, color, name in [(0, "steelblue", "Normal"), (1, "tomato", "Ataque")]:
        subset = df[df[TARGET] == label][feat]
        ax.hist(subset, bins=50, alpha=0.6, color=color, label=name, density=True)
    ax.set_title(feat)
    ax.legend()

plt.suptitle("Distribucion de features: Normal vs Ataque", fontsize=14)
plt.tight_layout()
plt.show()

# Correlacion
plt.figure(figsize=(10, 8))
sns.heatmap(df[FLOW_FEATURES].corr(), annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Correlacion entre features de flujo")
plt.tight_layout()
plt.show()

# ============================================================
# CELDA 5: Split train/test y escalado
# ============================================================
X = df[FLOW_FEATURES].values
y = df[TARGET].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f"Train: {X_train_sc.shape}  |  Test: {X_test_sc.shape}")
print(f"Train - Normal: {(y_train == 0).sum()}, Ataque: {(y_train == 1).sum()}")
print(f"Test  - Normal: {(y_test == 0).sum()}, Ataque: {(y_test == 1).sum()}")

# ============================================================
# CELDA 6: Entrenamiento con Keras (MLP para ESP32-S3)
# ============================================================
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

print(f"TensorFlow: {tf.__version__}")
print(f"Features: {len(FLOW_FEATURES)} | Clases: 2 (binario)")

# Red neuronal pequena optimizada para ESP32-S3
model = keras.Sequential([
    layers.Input(shape=(len(FLOW_FEATURES),)),
    layers.Dense(32, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(16, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.2),
    layers.Dense(8, activation="relu"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)

model.summary()

# Callbacks
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=10, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6
)

history = model.fit(
    X_train_sc, y_train,
    validation_split=0.15,
    epochs=100,
    batch_size=256,
    callbacks=[early_stop, reduce_lr],
    verbose=1,
)

# Grafico de entrenamiento
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history.history["loss"], label="Train")
axes[0].plot(history.history["val_loss"], label="Val")
axes[0].set_title("Loss")
axes[0].legend()

axes[1].plot(history.history["accuracy"], label="Train")
axes[1].plot(history.history["val_accuracy"], label="Val")
axes[1].set_title("Accuracy")
axes[1].legend()

plt.tight_layout()
plt.show()

# ============================================================
# CELDA 7: Evaluacion del modelo Keras
# ============================================================
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    f1_score, precision_score, recall_score, roc_auc_score, roc_curve
)

y_proba = model.predict(X_test_sc, verbose=0).flatten()
y_pred  = (y_proba >= 0.5).astype(int)

acc  = accuracy_score(y_test, y_pred)
f1   = f1_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec  = recall_score(y_test, y_pred)
auc  = roc_auc_score(y_test, y_proba)

print(f"Accuracy  : {acc:.4f}")
print(f"F1        : {f1:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"AUC       : {auc:.4f}\n")

print(classification_report(
    y_test, y_pred,
    target_names=["Normal", "Ataque"],
    zero_division=0
))

# Confusion matrix + ROC
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Normal", "Ataque"],
            yticklabels=["Normal", "Ataque"], ax=axes[0])
axes[0].set_title("Matriz de confusion")
axes[0].set_ylabel("Real")
axes[0].set_xlabel("Predicho")

fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, color="darkorange", label=f"AUC = {auc:.3f}")
axes[1].plot([0, 1], [0, 1], "k--", alpha=0.3)
axes[1].set_title("Curva ROC")
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].legend()

plt.tight_layout()
plt.show()

# ============================================================
# CELDA 8: Importancia de features por permutacion
# ============================================================
from sklearn.inspection import permutation_importance
from sklearn.base import BaseEstimator, ClassifierMixin

class KerasWrapper(BaseEstimator, ClassifierMixin):
    def __init__(self, keras_model):
        self.keras_model = keras_model
        self.classes_ = np.array([0, 1])
    def fit(self, X, y):
        return self
    def predict(self, X):
        return (self.keras_model.predict(X, verbose=0).flatten() >= 0.5).astype(int)

wrapper = KerasWrapper(model)
perm = permutation_importance(wrapper, X_test_sc, y_test, n_repeats=5,
                              random_state=SEED, scoring="f1", n_jobs=1)

indices = np.argsort(perm.importances_mean)[::-1]
print("Importancia de features (permutacion):\n")
for i, idx in enumerate(indices):
    bar = "█" * int(perm.importances_mean[idx] * 100)
    print(f"  {i+1:2d}. {FLOW_FEATURES[idx]:<20s} {perm.importances_mean[idx]:.4f}  {bar}")

plt.figure(figsize=(10, 5))
plt.bar(range(len(FLOW_FEATURES)), perm.importances_mean[indices], color="steelblue")
plt.xticks(range(len(FLOW_FEATURES)),
           [FLOW_FEATURES[i] for i in indices], rotation=45, ha="right")
plt.title("Importancia de features para deteccion de ataque")
plt.tight_layout()
plt.show()

# ============================================================
# CELDA 9: Estimacion de tamanio para ESP32-S3
# ============================================================
total_params = model.count_params()
size_float32_kb = total_params * 4 / 1024
size_int8_kb    = total_params * 1 / 1024

print(f"Parametros totales : {total_params}")
print(f"Tamanio float32    : {size_float32_kb:.1f} KB")
print(f"Tamanio int8 (TFLite): {size_int8_kb:.1f} KB")
print(f"\nESP32-S3: 16 MB Flash, 8 MB PSRAM, 512 KB SRAM")
print(f"  Flash  : {'OK' if size_int8_kb < 14000 else 'NO CABE'}")
print(f"  PSRAM  : {'OK' if size_int8_kb < 7000 else 'NO CABE'}")
print(f"  SRAM   : {'OK' if size_int8_kb < 300 else 'Usar PSRAM'}")

# ============================================================
# CELDA 10: Simulacion de inferencia en ESP32-S3
# ============================================================
ESP32_CPU_MHZ = 240
HOST_GHZ      = 3.0
ESP32_GHZ     = ESP32_CPU_MHZ / 1000
POWER_MW      = 80

N_SIM = min(2000, len(X_test))
idx_sim = np.random.choice(len(X_test), N_SIM, replace=False)

latencies = []
preds = []

print(f"Ejecutando {N_SIM} inferencias simuladas...\n")
for i in idx_sim:
    sample = X_test_sc[i].reshape(1, -1)
    t0 = time.perf_counter()
    pred = (model.predict(sample, verbose=0).flatten()[0] >= 0.5).astype(int)
    t1 = time.perf_counter()

    lat_esp32_us = (t1 - t0) * 1e6 * (HOST_GHZ / ESP32_GHZ)
    latencies.append(lat_esp32_us)
    preds.append(pred)

preds = np.array(preds)
acc_sim = accuracy_score(y_test[idx_sim], preds)
f1_sim  = f1_score(y_test[idx_sim], preds)

avg_lat = np.mean(latencies)
p99_lat = np.percentile(latencies, 99)
throughput = 1e6 / avg_lat

print("="*55)
print("   REPORTE ESP32-S3 (16MB Flash, 8MB PSRAM, 240MHz)")
print("="*55)
print(f"  Muestras          : {N_SIM}")
print(f"  Accuracy          : {acc_sim:.4f}")
print(f"  F1                : {f1_sim:.4f}")
print(f"  Latencia promedio : {avg_lat:.1f} us ({avg_lat/1000:.2f} ms)")
print(f"  Latencia p99      : {p99_lat:.1f} us")
print(f"  Throughput        : {throughput:.0f} predicciones/seg")
print(f"  Energia/inf       : {POWER_MW * avg_lat / 1e6 * 1e3:.4f} uJ")
print("="*55)

plt.figure(figsize=(10, 4))
plt.plot(latencies, alpha=0.5, linewidth=0.5, color="darkorange")
plt.axhline(avg_lat, color="red", linestyle="--", label=f"Media: {avg_lat:.0f} us")
plt.title("Latencia simulada ESP32-S3 @ 240MHz")
plt.xlabel("Muestra")
plt.ylabel("Latencia (us)")
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# CELDA 11: Exportar modelo en todos los formatos
# ============================================================
from pathlib import Path
import json

EXPORT_DIR = Path("export_mqtt_ids_model")
EXPORT_DIR.mkdir(exist_ok=True)

# 1) feature_order.csv
pd.Series(FLOW_FEATURES).to_csv(EXPORT_DIR / "feature_order.csv", index=False, header=False)
print("feature_order.csv guardado.")

# 2) label_map.json
label_map = {"normal": 0, "attack": 1}
with open(EXPORT_DIR / "label_map.json", "w") as f:
    json.dump(label_map, f, indent=2)
print("label_map.json guardado.")

# 3) scaler_params.json
with open(EXPORT_DIR / "scaler_params.json", "w") as f:
    json.dump({
        "mean":     scaler.mean_.tolist(),
        "std":      scaler.scale_.tolist(),
        "features": FLOW_FEATURES,
    }, f, indent=2)
print("scaler_params.json guardado.")

# 4) Formato .keras (recomendado TF2.13+)
keras_path = EXPORT_DIR / "mqtt_ids.keras"
model.save(keras_path)
print(f"mqtt_ids.keras guardado ({keras_path.stat().st_size / 1024:.1f} KB)")

# 5) Formato .h5 (compatible legacy)
h5_path = EXPORT_DIR / "mqtt_ids.h5"
model.save(h5_path)
print(f"mqtt_ids.h5 guardado ({h5_path.stat().st_size / 1024:.1f} KB)")

# 6) SavedModel (para TF Serving / conversion)
savedmodel_path = EXPORT_DIR / "saved_model"
model.save(savedmodel_path, include_optimizer=False)
print(f"saved_model/ guardado.")

# 7) TFLite float32
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_f32 = converter.convert()
tflite_f32_path = EXPORT_DIR / "mqtt_ids_float32.tflite"
with open(tflite_f32_path, "wb") as f:
    f.write(tflite_f32)
print(f"mqtt_ids_float32.tflite ({len(tflite_f32) / 1024:.1f} KB)")

# 8) TFLite int8 (cuantizacion completa para ESP32)
def representative_dataset():
    for i in range(min(500, len(X_train_sc))):
        yield [X_train_sc[i:i+1].astype(np.float32)]

converter_int8 = tf.lite.TFLiteConverter.from_keras_model(model)
converter_int8.optimizations = [tf.lite.Optimize.DEFAULT]
converter_int8.representative_dataset = representative_dataset
converter_int8.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter_int8.inference_input_type = tf.int8
converter_int8.inference_output_type = tf.int8

tflite_int8 = converter_int8.convert()
tflite_int8_path = EXPORT_DIR / "mqtt_ids_int8.tflite"
with open(tflite_int8_path, "wb") as f:
    f.write(tflite_int8)
print(f"mqtt_ids_int8.tflite ({len(tflite_int8) / 1024:.1f} KB)")

# Resumen
print("\n--- Archivos exportados ---")
for archivo in sorted(EXPORT_DIR.rglob("*")):
    if archivo.is_file():
        print(f"  {str(archivo.relative_to(EXPORT_DIR)):<40s}  {archivo.stat().st_size / 1024:.1f} KB")

# ============================================================
# CELDA 12: Verificar precision del TFLite int8
# ============================================================
interpreter = tf.lite.Interpreter(model_path=str(tflite_int8_path))
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_scale, input_zero  = input_details[0]["quantization"]
output_scale, output_zero = output_details[0]["quantization"]

print(f"Input  : dtype={input_details[0]['dtype']}, scale={input_scale}, zero={input_zero}")
print(f"Output : dtype={output_details[0]['dtype']}, scale={output_scale}, zero={output_zero}")

y_pred_tflite = []
for i in range(len(X_test_sc)):
    sample = X_test_sc[i:i+1].astype(np.float32)
    sample_q = (sample / input_scale + input_zero).astype(np.int8)

    interpreter.set_tensor(input_details[0]["index"], sample_q)
    interpreter.invoke()

    output_q = interpreter.get_tensor(output_details[0]["index"])
    output_f = (output_q.astype(np.float32) - output_zero) * output_scale
    pred = 1 if output_f.flatten()[0] >= 0.5 else 0
    y_pred_tflite.append(pred)

y_pred_tflite = np.array(y_pred_tflite)

acc_tflite = accuracy_score(y_test, y_pred_tflite)
f1_tflite  = f1_score(y_test, y_pred_tflite)

print(f"\n{'Metrica':<20} {'Keras float32':<18} {'TFLite int8':<18} {'Degradacion'}")
print("-" * 70)
print(f"{'Accuracy':<20} {acc:<18.4f} {acc_tflite:<18.4f} {(acc - acc_tflite)*100:.3f}%")
print(f"{'F1':<20} {f1:<18.4f} {f1_tflite:<18.4f} {(f1 - f1_tflite)*100:.3f}%")

